[general]
import = [
	"~/.config/alacritty/theme/everforest_dark.toml", 
]
live_config_reload = true

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "FiraCode Nerd Font Mono"
#family = "GeistMono Nerd Font Mono"
#style = "Regular"
style = "Light"

[font.offset]
x = 1
y = 1

[scrolling]
history = 100000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_padding = true
decorations = "buttonless"
decorations_theme_variant = "Dark"
opacity = 0.8
option_as_alt = "OnlyLeft"
blur = true

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 10
y = 0
