import = [
	"~/.config/alacritty/theme/gruvbox_material.toml", 
]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[font]
size = 18.5

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Light"

[font.offset]
x = 1
y = 5

[scrolling]
history = 100000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "buttonless"
decorations_theme_variant = "Dark"
opacity = 0.9
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 10
y = 0
