#[source.crates-io]
#replace-with = "rustcc"
#
#[source.rustcc]
#registry = "git://crates.rustcc.cn/crates.io-index"

#[source.crates-io]
#registry = "https://github.com/rust-lang/crates.io-index"
#replace-with = 'sjtug'

[source.sjtug]
registry = "https://mirrors.sjtug.sjtu.edu.cn/git/crates.io-index"

[source.crates-io]
replace-with = 'rsproxy'

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"

[build]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

#[unstable]
#codegen-backend = true

[profile.dev]
opt-level = 1
#codegen-backend = "cranelift"
overflow-checks = false

[profile.release]
lto = true
