[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = []

language-server = { command = "rust-analyzer" }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["go.mod", "go.work"]
max-line-length = 99
config = { "formatting.gofumpt" = true }

#language-server = { command = "golangci-lint" }
#language-server = { command = "golangci-lint",  args=["run", "--out-format", "json"]}
#formatter = { command = "gofumpt" }
# TODO: gopls needs utf-8 offsets?
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py"]
roots = []

language-server = { command = "ruff-lsp" }
config = { settings = { args = [] } }
# language-server = { command = "pyright" }
# TODO: pyls needs utf-8 offsets
indent = { tab-width = 2, unit = "  " }

