[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = []

language-server = { command = "rust-analyzer" }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "go"
scope = "source.go"
injection-regex = "go"
file-types = ["go"]
roots = ["Gopkg.toml", "go.mod"]

#language-server = { command = "gopls" }
language-server = { command = "golangci-lint-langserver" }
# TODO: gopls needs utf-8 offsets?
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py"]
roots = []

language-server = { command = "pyright" }
# TODO: pyls needs utf-8 offsets
indent = { tab-width = 2, unit = "  " }

