[colors]
transparent_background_colors = true

[colors.bright]
black = "#585858"
blue = "#ffaf00"
cyan = "#00afaf"
green = "#afd700"
magenta = "#ffaf00"
red = "#5faf5f"
white = "#5f8787"
yellow = "#af87d7"

[colors.cursor]
cursor = "#808080"
text = "#1c1c1c"

[colors.normal]
black = "#1c1c1c"
blue = "#5fafd7"
cyan = "#d7875f"
green = "#5faf00"
magenta = "#808080"
red = "#af005f"
white = "#d0d0d0"
yellow = "#d7af5f"

[colors.primary]
background = "#1c1c1c"
foreground = "#808080"
